<?php

require_once(dirname(__FILE__) . '/AbstractTest.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-22 at 09:11:24.
 */
class Contactlab_Template_Model_Newsletter_Processor_CartTest extends Contactlab_Template_Model_Newsletter_Processor_AbstractTest {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        parent::setUp();
        $this->object = Mage::getModel('contactlab_template/newsletter_processor_cart');
        $this->object->setStoreId($this->getStoreId());
    }

    /**
     * @small
     * @covers Contactlab_Template_Model_Newsletter_Processor_Cart::getProcessorCode
     */
    public function testGetProcessorCode() {
        $this->log("testGetProcessorCode");
        $this->assertEquals('cart', $this->object->getProcessorCode(), "Processor code should be \"cart\"");
    }

    /**
     * @medium
     * Test customers
     */
    public function testCustomers() {
        return parent::testCustomers();
    }

    /**
     * Test subscription
     * @medium
     * @param Mage_Customer_Model_Customer[] $customers Customers
     * @depends testCustomers
     */
    public function testSubscription(array $customers) {
        return parent::testSubscription($customers);
    }

    /**
     * 
     * @param Mage_Customer_Model_Customer[] $customers Customers
     * @medium
     * @depends testSubscription
     */
    public function testCart(array $customers) {
        $this->log("testCart");
        $this->doTestGeneratedCustomers($customers);

        // These customers wont receive an email
        $voidCart = $this->generateVoidCart($customers[0], $this);
        $this->assertEmpty($voidCart->getAllVisibleItems(), "This customer shouldn't have items in cart");

        /* @var $notVoidCart Mage_Sales_Model_Quote[] */
        $notVoidCart = array(
            $this->generateOldCart($customers[1], $this),
            $this->generateCart($customers[2], $this),
            $this->generateYoungCart($customers[3], $this),
            $this->generateCart($customers[4], $this),
        );
        foreach ($notVoidCart as $cart) {
            $this->assertNotEmpty($cart->getAllVisibleItems(), "This customer should have items in cart");
        }
    }


    /**
     * Test filters.
     * @medium
     * @param Mage_Customer_Model_Customer[] $customers Customers
     * @depends testCart
     */
    public function testFilters(array $customers) {
        return $this->doTestFilters($customers, "CART");
    }
}
