<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-23 at 15:05:42.
 */
class Contactlab_Template_Helper_DataTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Contactlab_Template_Helper_Data
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = Mage::helper('contactlab_template');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Contactlab_Template_Helper_Data::scan
     */
    public function testScan() {
        $templates = Mage::getResourceModel("newsletter/template_collection")
            ->loadActiveTemplatesForCron();
        $this->assertNotEmpty($templates->getItems(), "No active templates for cron");
    }

    /**
     * @covers Contactlab_Template_Helper_Data::getAvailableStores
     */
    public function testGetAvailableStores() {
        $this->assertNotEmpty($this->object->getAvailableStores()->getItems(),
                "There should be some available stores to test");
    }

    /**
     * @covers Contactlab_Template_Helper_Data::isStoreEnabled
     */
    public function testIsStoreEnabled() {
        $stores = $this->object->getAvailableStores();
        $found = false;
        $storeId = $GLOBALS['store_id'];
        $this->assertGreaterThan(0, $storeId, "Store id should be greater than 0");
        foreach ($stores as $store) {
            if ($store->getStoreId() == $storeId) {
                $found = true;
                break;
            }
        }
        $this->assertTrue($found, "Store $storeId should be enabled to cron execution!");
    }

    /**
     * Test SFTP Connection.
     * @medium
     */
    public function testSFTPConnection() {
        /* @var $uploader Contactlab_Template_Model_Newsletter_XmlDelivery_Uploader */
        $uploader = Mage::getModel('contactlab_template/newsletter_xmlDelivery_uploader');
        $uploader->setStoreId($GLOBALS['store_id']);
        /* @var $sftp Contactlab_Commons_Model_Ssh_Net_SFTP */
        try {
            $sftp = $uploader->getSFTPConnection();
            $this->assertTrue($sftp !== false, "SFTP object is false!");
        } catch (Zend_Exception $e) {
            $this->assertTrue(false, "Exception during login (" . $e->getMessage() . ")!");
        }
        $sftp->_disconnect(0);
    }
    
    /**
     * @covers Contactlab_Template_Helper_Data::checkNewsletterQueueReport
     * @depends testSFTPConnection
     * @medium
     */
    public function testCheckNewsletterQueueReport() {
        /* @var $uploader Contactlab_Template_Model_Newsletter_XmlDelivery_Uploader */
        $uploader = Mage::getModel('contactlab_template/newsletter_xmlDelivery_uploader');
        $uploader->setStoreId($GLOBALS['store_id']);
        /* @var $sftp Contactlab_Commons_Model_Ssh_Net_SFTP */
        $sftp = $uploader->getSFTPConnection();

        $this->assertTrue(true);
        
        $sftp->_disconnect(0);
    }
}
