<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-23 at 10:07:59.
 */
class Contactlab_Template_Model_SimpleXMLExtendedTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Contactlab_Template_Model_SimpleXMLExtended
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = simplexml_load_string("<document/>", 'Contactlab_Template_Model_SimpleXMLExtended');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Contactlab_Template_Model_SimpleXMLExtended::addCData
     * @todo   Implement testAddCData().
     */
    public function testAddCData()
    {
        $str = '$this->object';
        $this->object->addCData($str);
        $this->assertEquals($str, (string) $this->object, "CDATA content not equal of the one inserted");
    }
}
