<div class="grid box-left" style="margin-top: 5px">
    <div class="hor-scroll">
        <h3 style="margin-top: 10px">Recurring email</h3>
        <table style="border-collapse: collapse">
            <colgroup>
                <col style="width: 200px"/>
                <col/>
                <col/>
            </colgroup>
            <tr><td/><td colspan="2"><?php echo $this->getChildHtml('contactlab.template.queue') ?></td></tr>
            <tr><?php echo $this->getChildHtml('contactlab.template.email') ?>
            <td><a href="<?php echo $this->getUrl('adminhtml/system_config/edit', array('section' => 'contactlab_template')) ?>"><?php echo $this->__('Configure') ?></a></td>
            </tr>
        </table>
    </div>
</div>
