<div class="grid box-left" style="margin-top: 5px">
    <div class="hor-scroll">
        <h3 style="margin-top: 10px">Recurring email</h3>
        <table style="border-collapse: collapse">
            <colgroup>
                <col style="width: 200px"/>
                <col/>
            </colgroup>
            <tr><td/><td><?php echo $this->getChildHtml('contactlab.template.queue') ?></td></tr>
            <tr><?php echo $this->getChildHtml('contactlab.template.email') ?></tr>
        </table>
    </div>
</div>
